{% set version = "1.1.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-genlib
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GENLIB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GENLIB/GENLIB_{{ version }}.tar.gz
  sha256: f686074dec99e5d775e44d7e4926d945f8725fd7f00a16d7d558d275c14e928c

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-matrix
    - r-rcpp >=0.9.10
    - r-bootstrap
    - r-doparallel
    - r-foreach
    - r-kinship2
    - r-lattice
    - r-quadprog
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bh
    - r-matrix
    - r-rcpp >=0.9.10
    - r-bootstrap
    - r-doparallel
    - r-foreach
    - r-kinship2
    - r-lattice
    - r-quadprog

test:
  commands:
    - $R -e "library('GENLIB')"           # [not win]
    - "\"%R%\" -e \"library('GENLIB')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GENLIB
  license: GPL-2.0-or-later
  summary: Genealogical data analysis including descriptive statistics (e.g., kinship and inbreeding coefficients) and gene-dropping simulations.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: GENLIB
# Type: Package
# Title: Genealogical Data Analysis
# Version: 1.0.6
# Date: 2018-05-27
# Authors@R: c( person("Louis",			"Houde",        role="aut"), person("Jean-Francois",	"Lefebvre",	role="aut", email="jf_lef@yahoo.ca"), person("Valery",		"Roy-Lagace",	role="aut"), person("Sebastien",		"Lemieux",	role="aut"), person("Michael J.",		"Fromberger",	role="ctb"), person("Marie-Helene",	"Roy-Gagnon",	role="cre", email="mroygagn@uottawa.ca"))
# Description: Genealogical data analysis including descriptive statistics (e.g., kinship and inbreeding coefficients) and gene-dropping simulations.
# License: GPL (>= 2)
# LazyLoad: yes
# Depends: R (>= 3.1.0), Rcpp (>= 0.9.10)
# Imports: kinship2, methods, bootstrap, Matrix, lattice, quadprog, foreach, parallel, doParallel
# LinkingTo: Rcpp
# Packaged: 2018-05-28 02:20:35 UTC; lefjea01
# NeedsCompilation: yes
# Author: Louis Houde [aut], Jean-Francois Lefebvre [aut], Valery Roy-Lagace [aut], Sebastien Lemieux [aut], Michael J. Fromberger [ctb], Marie-Helene Roy-Gagnon [cre]
# Maintainer: Marie-Helene Roy-Gagnon <mroygagn@uottawa.ca>
# Repository: CRAN
# Date/Publication: 2018-05-30 17:51:45 UTC
