travis:
  secure:
    BINSTAR_TOKEN: fgBq3sBR9XEy3I+jASfk4z0XxXkZIi21850KBdMGDxQ/Ieoyvi3Wx+jhq2niyxrMsi2cZ1m43rYJeCFK+YA3b0kKE3hA5QKbNoQ6Kv7qKnmYiYCqUWiMjEtLsCqP6bJy/1bK1MWCNJ5tLSI4Gmx7fwzAaC0eQxETBI48n0GADKz1SDTRrmf1gZVWicskWaVsW+xuKspvcHA7vJ98he41vFiWCis33gaL8o565Qzhwm6b3ZTeFZGZ2EdGm0/YV25h5utyYXWrfMQ11CcBW5WtJ6g64hzZKo5ORZ0ubtZ2u0/5A4MsBt7JaUMpYqo6sCQudnJHCAvUWZ/kQTcqFJiPV6sVJYL9pgaoqsqqlaLMLnWfNM5Q71NvYt5Hs1COAQQFLSiw3VKlBueUftjUvtPSb5mp+Cg4urax++Tti9N9rtr6/Tm6rE8QjHIpl7qHYPks3CEZYGoYaPuea329oR/hjVHk9teDvrs4KGii5cimtVSsNxsHvSScHW9cOmL1T/wTFGsqM23o4A2l8mu5ww1tT4/e6wHYEVzbD1HNuGoF+h3Q560KQJgyJAklHm8Ibo0lLAYZezoLAs5EGg/SWbrjJla2jXWCqpNlg93on12YMMf8vCBXMW/GEO0/D6HsvhtZoIfy5c7ZEdPLpEY/P6pa04HhpRJYkfkvUn2m+fgX6TE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
